# Generated by Django 4.2.2 on 2023-07-16 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R')], max_length=1)),
                ('is_library_book', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(max_length=500)),
                ('grade_level', models.CharField(choices=[('AC', 'After School'), ('PA', 'Pre-After'), ('G1', 'Graduate 1'), ('G2', 'Graduate 2'), ('G3', 'Graduate 3'), ('ADV', 'Advanced'), ('B', 'Baby'), ('K2', 'Kindergarten 2'), ('K1', 'Kindergarten 1'), ('P2', 'PreSchool 2'), ('P1', 'PreSchool 1')], max_length=5)),
                ('isbn', models.CharField(max_length=13)),
            ],
        ),
    ]
